### ISSUE TITLE
emit - async call via event source

### ISSUE THREAD

**Issue by mthenw** [serverless/stdlib-nodejs#7]
Serverless framework already support different event sources (S3, APIG). Instead of explicitly calling `callAsync` it would be more flexible to provide a way to emit events (from within function) that other function can treat as an event source.

### Example

serverless.yml:
```
functions:
  sendWelcomeEmail:
    events:
      - function: userCreated
```

Function `sendWelcomeEmail` is async called every time `userCreated` event is emitted from functions in the same service.

userCreate.js:
```
sdk.emit('userCreated', 'test@exmaple.com');
```

Optionally more advanced event source object can be defined:

```
functions:
  sendWelcomeEmail:
    events:
      - function:
        event: userCreated
        function: create # listen to userCreated events only emitted by create function
```
